[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
blaadje = { path = "../blaadje" }
cpal = "0.15.3"
ringbuf = "0.4.7"
clap = "4.5.32"
notify = "8.0.0"

[profile.dev]
opt-level = 3